# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Geonhwa Jeong

tagline:          'Geonhwa Jeong'
description:      'PhD Student'
url:              https://ghjeong12.github.io/
baseurl:          https://ghjeong12.github.io/

author:
  name:           'Geonhwa Jeong'
  url:            https://ghjeong12.github.io

paginate:         7
paginate_path:    "/posts/:num/"

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/ghjeong12/ghjeong12.github.io
